[package]
name = "libpacstall"
version = "0.1.5"
edition = "2024"
authors = [
    "Elsie <hwengerstickel@pm.me>"
]
description = "Backend API library for Pacstall"
repository = "https://github.com/Elsie19/libpacstall"
license = "GPL-3.0-or-later"
keywords = ["aur", "pacstall", "package-manager", "linux", "apt"]

[dependencies]
serde = { version = "1.0.219", optional = true, features = ["derive"] }
thiserror = "2.0.12"
url = "2.5.4"

[features]
serde = ["dep:serde", "serde/derive", "url/serde"]

[dev-dependencies]
reqwest = { version = "0.12.15", features = ["blocking"] }

[[example]]
name = "print_packages"
doc-scrape-examples = true
