[package]
name = "libpacstall"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", optional = true, features = ["derive"] }
thiserror = "2.0.12"

[features]
serde = ["dep:serde", "serde/derive"]
